extends Node
signal notice(title: String, detail: String, color: Color)
signal run_started()
signal enemy_died(position: Vector2, xp: int, kind: StringName, elite: bool)
signal damage_dealt(weapon: StringName, amount: float, position: Vector2, heavy: bool)
signal player_hurt(amount: float)
signal player_died()
signal pickup_collected(kind: StringName, value: int)
signal level_up(level: int)
signal inventory_changed()
signal run_ended(victory: bool)
signal impact(position: Vector2, magnitude: float, color: Color)
signal damage_resolved(info: DamageInfo, final: float)
signal status_applied(target: Node, effect: StatusEffect, stacks: int)
signal status_removed(target: Node, effect: StatusEffect)
signal entity_killed(kind: StringName, position: Vector2, by_player: bool)
signal guardian_defeated(stage: int, title: String)
signal regional_boss_defeated(region_id: String, title: String)
signal ability_used(id: StringName, position: Vector2)
signal reaction_triggered(kind: StringName, position: Vector2, amount: float)
signal weather_changed(id: StringName, title: String, detail: String)
signal affix_triggered(kind: StringName, position: Vector2)
signal achievement_unlocked(id: StringName, title: String)
